minor adjustments

diff --git a/roles/oh-my-zsh/templates/.zshrc.j2 b/roles/oh-my-zsh/templates/.zshrc.j2
--- a/roles/oh-my-zsh/templates/.zshrc.j2
+++ b/roles/oh-my-zsh/templates/.zshrc.j2
@@ -65,8 +65,16 @@ alias lsa='ls -a'
 alias lt='eza --tree --level=2 --long --icons --git'
 alias lta='lt -a'
 alias ff="fzf --preview 'batcat --style=numbers --color=always {}'"
-alias fd='fdfind'
-alias cd='z'
+alias cd="zd"
+zd() {
+  if [ $# -eq 0 ]; then
+    builtin cd ~ && return
+  elif [ -d "$1" ]; then
+    builtin cd "$1"
+  else
+    z "$@" && printf " \U000F17A9 " && pwd || echo "Error: Directory not found"
+  fi
+}
 
 # Directories
 alias ..='cd ..'
@@ -80,6 +88,11 @@ alias d='docker'
 alias bat='batcat'
 alias lzg='lazygit'
 alias lzd='lazydocker'
+
+# Browser
+open() {
+  xdg-open "$@" >/dev/null 2>&1
+}
 
 # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
 [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
