Rework and integrate some ideas from omakub (#1)

diff --git a/roles/oh-my-zsh/templates/.zshrc.j2 b/roles/oh-my-zsh/templates/.zshrc.j2
--- a/roles/oh-my-zsh/templates/.zshrc.j2
+++ b/roles/oh-my-zsh/templates/.zshrc.j2
@@ -1,123 +1,98 @@
-# PYENV PATHS
-export PYENV_ROOT="$HOME/.pyenv"
-export PYENV_SHIMS="$PYENV_ROOT/shims"
-export PYENV_PATH="$PYENV_ROOT/bin"
 
-# DOTFILES
-export DOTFILES_PATH="$HOME/.dotfiles/bin"
+. "$HOME/.cargo/env"
 
-# PATH
-export PATH="$PYENV_SHIMS:$PYENV_PATH:$DOTFILES_PATH:/usr/local/sbin:$PATH"
+# If you come from bash you might have to change your $PATH.
+# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
 
-# PREPARE SHELL FOR PYENV
-eval "$(pyenv init -)"
-eval "$(pyenv virtualenv-init -)"
-
-# SET SHELL-VAR IN CASE ZSH IS LANCHED TRHOUGH CUSTOM COMMAND
-export SHELL="/usr/bin/zsh"
-
-# OH-MY-ZSH
+# Path to your Oh My Zsh installation.
 export ZSH="$HOME/.oh-my-zsh"
 
-#ZSH_THEME="robbyrussell"
 ZSH_THEME="powerlevel10k/powerlevel10k"
 
-plugins=(git zsh-autosuggestions zsh-completions zsh-syntax-highlighting zsh-z)
+# Uncomment the following line to use case-sensitive completion.
+# CASE_SENSITIVE="true"
+
+# Uncomment the following line to use hyphen-insensitive completion.
+# Case-sensitive completion must be off. _ and - will be interchangeable.
+# HYPHEN_INSENSITIVE="true"
+
+# Uncomment one of the following lines to change the auto-update behavior
+zstyle ':omz:update' mode disabled  # disable automatic updates
+# zstyle ':omz:update' mode auto      # update automatically without asking
+# zstyle ':omz:update' mode reminder  # just remind me to update when it's time
+
+
+
+
+# Uncomment the following line if you want to change the command execution time
+# stamp shown in the history command output.
+# You can set one of the optional three formats:
+# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
+# or set a custom format using the strftime function format specifications,
+# see 'man strftime' for details.
+HIST_STAMPS="mm/dd/yyyy"
+
+
+plugins=(git zsh-autosuggestions zsh-completions zsh-syntax-highlighting)
 
 source $ZSH/oh-my-zsh.sh
 
-# DEFAULTS
-export ARCHFLAGS="-arch x86_64"
-export EDITOR='vim'
 
-# PIP
-export PIP_REQUIRE_VIRTUALENV=true
+# You may need to manually set your language environment
+# export LANG=en_US.UTF-8
 
-# NNN
-n () {
-  if [ -n $NNNLVL ] && [ "${NNNLVL:-0}" -ge 1 ]; then
-    echo "nnn is already running"
-    return
-  fi
-
-  export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
-
-  nnn "$@"
-
-  if [ -f "$NNN_TMPFILE" ]; then
-    . "$NNN_TMPFILE"
-    rm -f "$NNN_TMPFILE" > /dev/null
-  fi
-}
-
-kindc () {
-  cat <<EOF | kind create cluster --config=-
-kind: Cluster
-apiVersion: kind.x-k8s.io/v1alpha4
-nodes:
-- role: control-plane
-  kubeadmConfigPatches:
-  - |
-    kind: InitConfiguration
-    nodeRegistration:
-      kubeletExtraArgs:
-        node-labels: "ingress-ready=true"
-  extraPortMappings:
-  - containerPort: 80
-    hostPort: 80
-    protocol: TCP
-  - containerPort: 443
-    hostPort: 443
-    protocol: TCP
-EOF
-}
-
-# ALIASES
-alias cat='bat --paging=never --theme="base16"'
-alias nnn='nnn -e'
-# alias ls='nnn -e'
-alias grep='grep --color'
-alias ll='n -Hde'
-# alias la='ls -A'
-alias ssh='TERM="xterm-256color" ssh'
-alias rebase='git fetch --all --prune --prune-tags && git rebase'
-alias woof="k9s"
-
-# The next line sources a private environment file if it exists
-if [ -f "$HOME/.zsh_public" ]; then . "$HOME/.zsh_public"; fi
-if [ -f "$HOME/.zsh_private" ]; then . "$HOME/.zsh_private"; fi
-
-# TODO : cleanup scripting below
-
-# ITERM (MACOS ONLY)
-test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
-test -e /usr/share/nvm/init-nvm.sh && source /usr/share/nvm/init-nvm.sh
-
-[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"
-
-# The next line updates PATH for the Google Cloud SDK.
-if [ -f "$HOME/Development/google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/Development/google-cloud-sdk/path.zsh.inc"; fi
-
-# The next line enables shell command completion for gcloud.
-if [ -f "$HOME/Development/google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/Development/google-cloud-sdk/completion.zsh.inc"; fi
-
-# >>> conda initialize >>>
-# !! Contents within this block are managed by 'conda init' !!
-__conda_setup="$('/opt/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
-if [ $? -eq 0 ]; then
-    eval "$__conda_setup"
+# Preferred editor for local and remote sessions
+if [[ -n $SSH_CONNECTION ]]; then
+  export EDITOR='vim'
 else
-    if [ -f "/opt/miniconda3/etc/profile.d/conda.sh" ]; then
-        . "/opt/miniconda3/etc/profile.d/conda.sh"
-    else
-        export PATH="/opt/miniconda3/bin:$PATH"
-    fi
+  export EDITOR='nvim'
 fi
-unset __conda_setup
-# <<< conda initialize <<<
 
-# initialize golang
-if [ -f "/etc/profile.d/golang.sh" ]; then . "/etc/profile.d/golang.sh"; fi
+# Compilation flags
+export ARCHFLAGS="-arch $(uname -m)"
+
+if command -v zoxide &> /dev/null; then
+  eval "$(zoxide init zsh)"
+fi
+
+if command -v fzf &> /dev/null; then
+  eval "$(fzf --zsh)"
+fi
+
+# File system
+alias ls='eza -lh --group-directories-first --icons=auto'
+alias lsa='ls -a'
+alias lt='eza --tree --level=2 --long --icons --git'
+alias lta='lt -a'
+alias ff="fzf --preview 'batcat --style=numbers --color=always {}'"
+alias cd="zd"
+zd() {
+  if [ $# -eq 0 ]; then
+    builtin cd ~ && return
+  elif [ -d "$1" ]; then
+    builtin cd "$1"
+  else
+    z "$@" && printf " \U000F17A9 " && pwd || echo "Error: Directory not found"
+  fi
+}
+
+# Directories
+alias ..='cd ..'
+alias ...='cd ../..'
+alias ....='cd ../../..'
+
+# Tools
+n() { if [ "$#" -eq 0 ]; then nvim .; else nvim "$@"; fi; }
+alias g='git'
+alias d='docker'
+alias bat='batcat'
+alias lzg='lazygit'
+alias lzd='lazydocker'
+
+# Browser
+open() {
+  xdg-open "$@" >/dev/null 2>&1
+}
 
 # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
 [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
